spring.application.name=learningplatform
spring.datasource.url=jdbc:mysql://localhost:3306/learning_platform
spring.datasource.username=root
spring.datasource.password=root9090

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081